// All Workday companies — open tenants + session-cookie-required tenants
// open: true  → direct POST works without cookies
// open: false → needs session cookie handshake first

export interface WorkdayCompany {
  name: string;
  tenant: string;   // subdomain: <tenant>.wd1.myworkdayjobs.com
  path: string;     // career site path segment
  open: boolean;
}

export const WORKDAY_COMPANIES: WorkdayCompany[] = [
  // ── OPEN TENANTS (no session cookie needed) ──────────────────────────────
  { name: "AT&T",              tenant: "att",             path: "External",           open: true },
  { name: "Deloitte",          tenant: "deloitte",        path: "External",           open: true },
  { name: "USAA",              tenant: "usaa",            path: "USAA",               open: true },
  { name: "Southwest Airlines",tenant: "southwest",       path: "Southwest_Airlines_External", open: true },
  { name: "Guidehouse",        tenant: "guidehouse",      path: "External",           open: true },
  { name: "DXC Technology",    tenant: "dxc",             path: "ExternalCareers",    open: true },
  { name: "Santander",         tenant: "santander",       path: "External",           open: true },
  { name: "Corebridge",        tenant: "corebridge",      path: "External",           open: true },
  { name: "Applied Materials",  tenant: "amat",           path: "External",           open: true },
  { name: "Fidelity Investments",tenant: "fidelity",      path: "External",           open: true },
  { name: "Toyota NA",         tenant: "toyota",          path: "External",           open: true },
  { name: "Leidos",            tenant: "leidos",          path: "External",           open: true },
  { name: "SAIC",              tenant: "saic",            path: "External",           open: true },
  { name: "General Dynamics",  tenant: "gd",              path: "External",           open: true },
  { name: "Northrop Grumman",  tenant: "northropgrumman", path: "External",           open: true },
  { name: "Raytheon",          tenant: "rtx",             path: "External",           open: true },
  { name: "L3Harris",          tenant: "l3harris",        path: "External",           open: true },
  { name: "Booz Allen",        tenant: "bah",             path: "External",           open: true },
  { name: "CACI",              tenant: "caci",            path: "External",           open: true },
  { name: "ManTech",           tenant: "mantech",         path: "External",           open: true },
  { name: "KPMG",              tenant: "kpmg",            path: "Campus",             open: true },
  { name: "EY",                tenant: "ey",              path: "EY_External",        open: true },
  { name: "PwC",               tenant: "pwc",             path: "Global",             open: true },
  { name: "Grant Thornton",    tenant: "gt",              path: "External",           open: true },
  { name: "Capital One",       tenant: "capitalone",      path: "Capital_One",        open: true },
  { name: "TIAA",              tenant: "tiaa",            path: "External",           open: true },
  { name: "Principal Financial",tenant: "principal",      path: "External",           open: true },
  { name: "Lincoln Financial", tenant: "lincoln",         path: "External",           open: true },
  { name: "Humana",            tenant: "humana",          path: "External",           open: true },
  { name: "Cigna",             tenant: "cigna",           path: "External",           open: true },
  { name: "CVS Health",        tenant: "cvs",             path: "CVS_Health",         open: true },
  { name: "Elevance Health",   tenant: "elevancehealth",  path: "External",           open: true },
  { name: "Centene",           tenant: "centene",         path: "External",           open: true },
  { name: "Molina Healthcare", tenant: "molinahealthcare",path: "External",           open: true },
  { name: "Becton Dickinson",  tenant: "bd",              path: "External",           open: true },
  { name: "Baxter",            tenant: "baxter",          path: "External",           open: true },
  { name: "Stryker",           tenant: "stryker",         path: "External",           open: true },
  { name: "Zimmer Biomet",     tenant: "zimmerbiomet",    path: "External",           open: true },
  { name: "Hologic",           tenant: "hologic",         path: "External",           open: true },
  { name: "Halliburton",       tenant: "halliburton",     path: "External",           open: true },
  { name: "Baker Hughes",      tenant: "bhge",            path: "External",           open: true },
  { name: "Schlumberger",      tenant: "slb",             path: "External",           open: true },
  { name: "ConocoPhillips",    tenant: "conocophillips",  path: "External",           open: true },
  { name: "Phillips 66",       tenant: "phillips66",      path: "External",           open: true },
  { name: "Valero",            tenant: "valero",          path: "External",           open: true },
  { name: "Atmos Energy",      tenant: "atmosenergy",     path: "External",           open: true },
  { name: "Vistra",            tenant: "vistra",          path: "External",           open: true },
  { name: "NRG Energy",        tenant: "nrg",             path: "External",           open: true },
  { name: "Oncor",             tenant: "oncor",           path: "External",           open: true },
  { name: "Celanese",          tenant: "celanese",        path: "External",           open: true },
  { name: "Olin",              tenant: "olin",            path: "External",           open: true },
  { name: "Westrock",          tenant: "westrock",        path: "External",           open: true },
  { name: "FedEx",             tenant: "fedex",           path: "FedEx",              open: true },
  { name: "UPS",               tenant: "ups",             path: "UPS",                open: true },
  { name: "XPO",               tenant: "xpo",             path: "External",           open: true },
  { name: "Werner Enterprises",tenant: "werner",          path: "External",           open: true },
  { name: "Ryder",             tenant: "ryder",           path: "External",           open: true },
  { name: "Dollar General",    tenant: "dollargeneral",   path: "External",           open: true },
  { name: "Dollar Tree",       tenant: "dollartree",      path: "External",           open: true },
  { name: "Albertsons",        tenant: "albertsons",      path: "Albertsons",         open: true },
  { name: "Sysco",             tenant: "sysco",           path: "External",           open: true },
  { name: "HCA Healthcare",    tenant: "hca",             path: "External",           open: true },
  { name: "Community Health",  tenant: "communityhealth", path: "External",           open: true },
  { name: "Tenet Healthcare",  tenant: "tenethealth",     path: "External",           open: true },
  { name: "DaVita",            tenant: "davita",          path: "External",           open: true },

  // ── SESSION-COOKIE TENANTS (handshake required) ──────────────────────────
  { name: "JPMorgan Chase",    tenant: "jpmc",            path: "External",           open: false },
  { name: "Bank of America",   tenant: "bofa",            path: "External",           open: false },
  { name: "Wells Fargo",       tenant: "wf",              path: "WFExternal",         open: false },
  { name: "Citigroup",         tenant: "citi",            path: "External",           open: false },
  { name: "Goldman Sachs",     tenant: "gs",              path: "External",           open: false },
  { name: "Morgan Stanley",    tenant: "morganstanley",   path: "External",           open: false },
  { name: "American Express",  tenant: "aexp",            path: "AmexCareers",        open: false },
  { name: "BlackRock",         tenant: "blackrock",       path: "External",           open: false },
  { name: "Vanguard",          tenant: "vanguard",        path: "External",           open: false },
  { name: "Charles Schwab",    tenant: "schwab",          path: "External",           open: false },
  { name: "Microsoft",         tenant: "microsoft",       path: "External",           open: false },
  { name: "Amazon",            tenant: "amazon",          path: "External",           open: false },
  { name: "Google",            tenant: "google",          path: "External",           open: false },
  { name: "Meta",              tenant: "meta",            path: "External",           open: false },
  { name: "Apple",             tenant: "apple",           path: "External",           open: false },
  { name: "IBM",               tenant: "ibm",             path: "External",           open: false },
  { name: "Oracle",            tenant: "oracle",          path: "External",           open: false },
  { name: "Salesforce",        tenant: "salesforce",      path: "External",           open: false },
  { name: "SAP",               tenant: "sap",             path: "External",           open: false },
  { name: "Accenture",         tenant: "accenture",       path: "External",           open: false },
  { name: "Cognizant",         tenant: "cognizant",       path: "External",           open: false },
  { name: "Infosys",           tenant: "infosys",         path: "External",           open: false },
  { name: "Wipro",             tenant: "wipro",           path: "External",           open: false },
  { name: "TCS",               tenant: "tcs",             path: "External",           open: false },
  { name: "Boeing",            tenant: "boeing",          path: "External",           open: false },
  { name: "Lockheed Martin",   tenant: "lmco",            path: "External",           open: false },
  { name: "Walmart",           tenant: "walmart",         path: "External",           open: false },
  { name: "Target",            tenant: "target",          path: "External",           open: false },
  { name: "Home Depot",        tenant: "homedepot",       path: "External",           open: false },
  { name: "Lowe's",            tenant: "lowes",           path: "External",           open: false },
  { name: "Nike",              tenant: "nike",            path: "External",           open: false },
  { name: "Procter & Gamble",  tenant: "pg",              path: "External",           open: false },
  { name: "Johnson & Johnson", tenant: "jnj",             path: "External",           open: false },
  { name: "Abbott",            tenant: "abbott",          path: "External",           open: false },
  { name: "Medtronic",         tenant: "medtronic",       path: "External",           open: false },
  { name: "UnitedHealth Group",tenant: "uhg",             path: "External",           open: false },
  { name: "Pfizer",            tenant: "pfizer",          path: "External",           open: false },
  { name: "Merck",             tenant: "merck",           path: "External",           open: false },
  { name: "AbbVie",            tenant: "abbvie",          path: "External",           open: false },
  { name: "Bristol Myers",     tenant: "bms",             path: "External",           open: false },
  { name: "Eli Lilly",         tenant: "lilly",           path: "External",           open: false },
  { name: "Exxon Mobil",       tenant: "exxonmobil",      path: "External",           open: false },
  { name: "Chevron",           tenant: "chevron",         path: "External",           open: false },
];

export const JOB_KEYWORDS = [
  "data analyst","senior data analyst","sr data analyst","lead data analyst","staff data analyst",
  "principal data analyst","associate data analyst","junior data analyst","analytics analyst",
  "reporting analyst","data reporting analyst","insights analyst","data insights analyst",
  "analytics specialist","data specialist","decision support analyst",
  "business intelligence analyst","bi analyst","senior bi analyst","business intelligence developer",
  "bi developer","senior bi developer","business intelligence engineer","bi engineer",
  "power bi developer","power bi analyst","tableau developer","tableau analyst",
  "looker developer","looker analyst","data visualization analyst","data visualization developer",
  "reporting developer","dashboard developer","dashboard analyst",
  "business analyst","senior business analyst","sr business analyst","lead business analyst",
  "principal business analyst","associate business analyst","junior business analyst",
  "business systems analyst","senior business systems analyst","it business analyst",
  "technical business analyst","functional analyst","systems analyst","senior systems analyst",
  "enterprise systems analyst","erp analyst","sap analyst","salesforce analyst","crm analyst",
  "product analyst","product data analyst",
  "financial analyst","senior financial analyst","sr financial analyst","associate financial analyst",
  "finance analyst","fp&a analyst","senior fp&a analyst","financial planning analyst",
  "budget analyst","senior budget analyst","revenue analyst","revenue operations analyst",
  "revops analyst","pricing analyst","senior pricing analyst","cost analyst",
  "financial data analyst","finance data analyst","treasury analyst",
  "operations analyst","senior operations analyst","business operations analyst",
  "sales operations analyst","sales ops analyst","marketing operations analyst",
  "marketing analyst","gtm analyst","supply chain analyst","logistics analyst",
  "workforce management analyst","workforce analyst","capacity planning analyst",
  "demand planning analyst","procurement analyst","vendor analyst","strategy analyst",
  "strategic analyst","planning analyst",
  "data engineer","senior data engineer","sr data engineer","associate data engineer",
  "junior data engineer","etl developer","etl analyst","etl engineer",
  "data pipeline engineer","analytics engineer","senior analytics engineer",
  "data infrastructure engineer","data platform engineer","data integration engineer",
  "data integration analyst","database analyst","database developer","sql developer","sql analyst",
  "data warehouse analyst","data warehouse developer","data warehouse engineer",
  "snowflake developer","dbt developer","databricks analyst",
  "compliance analyst","compliance data analyst","senior compliance analyst",
  "regulatory analyst","data governance analyst","data quality analyst",
  "master data analyst","mdm analyst","data steward","senior data steward",
  "data management analyst","information analyst","records analyst",
  "risk analyst","risk data analyst","audit analyst","internal audit analyst",
];
